### ISSUE TITLE
The device /dev/nvme0n1 already has a volume group 

### ISSUE THREAD

**Issue by tosin2013** [flyemsafe/swygue-lvm#5]
The volume group does not exist but i am still getting this error. 
TASK [swygue-lvm : fail] **************************************************************************************************************************************
Thursday 15 August 2019  14:00:36 -0400 (0:00:00.274)       0:01:09.092 ******* 
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

The device /dev/nvme0n1 already has a volume group 
That does not match the given expected volume group name vg_qubi
Either change the value of host_device or remove the volume group 
Example:
           sudo vgremove  -ff -y
           sudo pvremove /dev/nvme0n1 -ff -y

**Comment by tosin2013** [comment]
nvme0n1       259:0    0 953.9G  0 disk 
└─nvme0n1p1   259:1    0 953.9G  0 part 
$ sudo vgdisplay
  --- Volume group ---
  VG Name               rhel
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  3
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                2
  Open LV               2
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               <463.76 GiB
  PE Size               4.00 MiB
  Total PE              118722
  Alloc PE / Size       118722 / <463.76 GiB
  Free  PE / Size       0 / 0   
  VG UUID               XF70FQ-81ox-wQ70-KsLO-zClq-gLVu-Ep37VD

**Comment by flyemsafe** [comment]
fixed in commit 2f3df67b21d6cd34719ba662e34051b3948dc3c7
